// Generated by CoffeeScript 1.4.0
var Scanner, bleScanner, callback;

Scanner = require("../../bluetooth-scanner");

callback = function(mac, name) {
  return console.log('Mac: ' + mac + ' Name: ' + name);
};

scanner = new Scanner("hci0", callback);

// Exit after 5s
setTimeout(scanner.destroy, 5000);
